### ISSUE TITLE
EA_GNSS10 - OW08 Rule should be set to false in JSON-file

### ISSUE THREAD

**Issue by btatar13** [IMFS-MMB/mmb-gui-electron#104]
**Describe the bug**
EA_GNSS10 - OW08 Rule should be set to false in JSON-file as 'NO SOLUTION FOUND'

**Comment by btatar13** [comment]
> Describe the bug
> EA_GNSS10 - OW08 Rule should be set to false in JSON-file as 'NO SOLUTION FOUND'

Somehow the JSON file is not read out properly, or is maybe wrong, as 11 is written into the JSON file in the dev version, but the Taylor rule is not available for selection

**Comment by j2L4e** [comment]
The rule ids were a legacy issue. Tules are referenced by their name now, so they're easier to maintain. (via efad878176bfe1da9c4cab24f2a7ec4f4daf1d3d)

**Comment by btatar13** [comment]
OK. I will download now everything once again and reinstall.

**Comment by btatar13** [comment]
Ok, new Version runs now, **but we should still delete OW08 from the policy rules as for OW08 there is no solution.**

**Comment by gboehl** [comment]
Yes, but is there a reason why you just did not do that? 

Next time, please send us a pull request with the updated JSON.

This also counts for the other bugs you reported here. They are valuable, but you could have just fixed them right away instead of reporting them. 

I'll push a fix in a second.
